### ISSUE TITLE
Where is the build directory?

### ISSUE THREAD

**Issue by elonmallin** [buptdbj/darknet-windows-linux#1]
Hi,

I'm trying to follow along with the windows installation but in step 1 it tells me to open `build\darknet\darknet.sln` but the path doesn't exist. I skimmed all text above the **How to compile with Windows** section but didn't find any mention of creating/getting a `build` folder.

Did I miss something or how can I get the build folder?

**Comment by beepmaster** [comment]
The build directory is under the "master" branch.
For information you will need the pthreadVC2.lib that is under the linux branch.

**Comment by elonmallin** [comment]
Ah thanks 👍
